### ISSUE TITLE
No Dark Theme in Timeline Window

### ISSUE THREAD

**Issue by davidkwong** [xeleh/enhancer#1] opened 2020-05-01 15:18 UTC
Hello, 

I found a bug where Timeline window is not working with the Dark Theme.  (V0.3.4)

![image](https://user-images.githubusercontent.com/3953867/80816194-e8be8c80-8b83-11ea-8b0d-34b0d496cd1a.png)

Window -> Sequencing -> Timeline  

I find this out when I am using Cinemachine 2.5.0 with Unity 2019.3.12f1

**Comment by Listwon** [comment] 2020-05-01 15:56
Cinemachine doesn't matter in this case. The problem is that Timeline depends on `EditorGUIUtility.isProSkin` value to switch between its skins.

**Comment by davidkwong** [comment] 2020-05-01 16:03
Maybe just have to live with this.

**Comment by xeleh** [comment] 2020-05-01 16:49
Yeah, @Listwon is right but we can solve this specific case. I just pushed a commit enabling a flag that will allow for it because it indicates whether our dark theme is enabled or not.

So pull the changes (or remove and reinstall the package) and then find and replace all references to `EditorGUIUtility.isProSkin` in the Timeline package code with `EditorGUIUtility.isProSkin || EditorPrefs.GetBool("darkTheme")`.

This is the result:

![Timeline-enhancer](https://user-images.githubusercontent.com/148356/80822781-ba6c9b80-8bdb-11ea-9673-792a1358d37f.png)

**Comment by davidkwong** [comment] 2020-05-01 19:39
@xeleh 

I have a null reference in my project after your latest commit .  Any idea ?

![image](https://user-images.githubusercontent.com/3953867/80836030-ce4ada00-8ba8-11ea-809b-13e47b1cd166.png)

**Comment by xeleh** [comment] 2020-05-01 20:33
A dumb mistake, sorry. Fixed now.

**Closed** 2020-05-01 20:35 UTC

**Comment by davidkwong** [comment] 2020-05-02 14:57
@xeleh 

This fix in 0.3.5. It's not working for me. (Unity 2019.3.12f1)

![image](https://user-images.githubusercontent.com/3953867/80867713-7cf32700-8c4a-11ea-8b05-a28c3c94149f.png)

**Comment by xeleh** [comment] 2020-05-02 15:15
Have you replaced all the references to `EditorGUIUtility.isProSkin` in the code of the Timeline package (`<your-project>/Library/PackageCache/com.unity.timeline@<version>`) as explained in the [Adapting](https://github.com/xeleh/enhancer/blob/master/Adapting.md) guide?

**Comment by xeleh** [comment] 2020-05-02 15:34
Ok, now I see the problem. When you reopen a project, Unity updates the local project package cache with the contents in the global cache, so the fix works but only during the current session. To make it permanent you need to modify the code in the [global package cache](https://docs.unity3d.com/Manual/upm-cache.html) instead.

**Comment by davidkwong** [comment] 2020-05-02 16:05
@xeleh 

I got it working now after changing the code in global package cache. Someday I might just write a utility to replace code within global  package cache for certain known modules. I keep exploring and see if I find more "rebel" cases.

**Comment by centuryhopper** [comment] 2020-09-02 14:33
@xeleh Hello Xeleh, which script in (<your-project>/Library/PackageCache/com.unity.timeline@<version>) am I supposed to modify? And which part in that script? I don't know what to do with the global cache documentation you shared before :'(

Thank you for your help🙏

**Comment by xeleh** [comment] 2020-09-03 05:48
You need to modify the scripts of the package but in the global cache. That global cache documentation I shared indicates where is the cache stored in your system. For example, in Windows this location is `%ALLUSERSPROFILE%\Unity\cache` where `%ALLUSERSPROFILE%` is an environment variable which in Windows 10 equals to `C:\ProgramData`. So the path of the package containing the files you need to modify will be `C:\ProgramData\Unity\cache\packages\com.unity.timeline@<version>`.

Check the [Adapting "rebel" cases](https://github.com/xeleh/enhancer/blob/master/Adapting.md) guide for information on which parts of the scripts you need to modify.
